---
title: "Complexity Plot"
author: "Christian Stenbro"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/christianstenbro/Programming/notation_chain_analysis/output") # change this path
```

```{r}
library(tidyverse)
library(rethinking)
```

```{r}
# loading data
d <- read.csv("complexity_list.csv", header = FALSE)
d <- d %>% rename("perimeter" = "V1", 
             "area" = "V2" , 
             "complexity" = "V3")
```

```{r}
# adding identity row
id <-  seq(1:9)
d <- d %>% mutate("id" = id, .before = "perimeter")
```


```{r}
# plotting complexity
pdf('complexity_development_3.pdf', width = 20 , height = 10)

plot( x = d$id , y = d$complexity , 
      xlab="Chain link ID" , ylab="Perimetric complexity" ,
      main="Complexity development" , ylim=c(0,1000) , xlim=c(0,10) , xaxt = "n" ,
      col = "blue" , type = "b" , pch=16 , cex = 2 , cex.main = 2.5 , cex.axis = 1.2, cex.lab = 1.2 , )
ticks <- c(1, 2, 3, 4, 5, 6, 7, 8, 9)
axis( side = 1 , at = ticks , labels = T )

dev.off()
```

